### ISSUE TITLE
[blog-2019-10-20-local-linux-user-tries-freebsd] <Add title here>

### ISSUE THREAD

**Issue by bsdphk** [Arnavion/www-arnavion-dev#1]
Re morsing things on LEDs:

On freebsd you can
    echo Hello World | morse -l > /dev/led/led0

**Comment by Arnavion** [comment]
Thanks. I guess I should make it clearer in the blog post, but the Raspberry Pis are running Raspbian, not FreeBSD. Raspbian's default repos don't seem to have `morse`; they do have `morsegen` but that just transcodes to `.` and `-` without any timing.

Edit: And regardless, the Raspberry Pi's LED driver doesn't understand `*` and `_` like the FreeBSD driver anyway, so the timing has to be supplied by the program.
